# Welcome to Jekyll!

# Website settings
title: "Nuwanda22"
description: "Nuwanda22's blog,use Jekyll and github pages."
keywords: "Nuwanda22,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://nuwanda22.github.io/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Nuwanda'
  first_name: 'Jun'
  last_name: 'Seongwoo'
  email: 'njk230@gmail.com'
  facebook_username: 'nuwanda22'
  github_username: 'nuwanda22'
  head_img: 'static/img/landing/Profile.jpg'
  desc: 'I am a Full Stack engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'ko'
    flag: 'static/img/flags/South-Korea.png'

# blog img path
img_path: 'https://nuwanda22.github.io/static/img/blog'

# comment
disqus:
  name: nuwanda22
  public_key: UKkBbYt1IR5FJpkJ1RWIPVbisJT8QTe3KgGw2OXXxnUeE8HW7SavZDvXex7wrkTV

# google analytics
ga:
  id: UA-87910638-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
