# Welcome to Jekyll!

# Website settings
title: Blog of Nuwanda 
description: Nuwanda's blog,use Jekyll and github pages.
keywords: Nuwanda22,blog,Jekyll,github,gh-pages
baseurl: 
url: https://nuwanda22.github.io
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author -- index page "about me" section
author:
  name: Kyle John
  first_name: Kyle
  last_name: John
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: Nuwanda22
  linkedin_id: kyle-john-0603b2117
  facebook_username: nuwanda22
  # twitter_username: jiakun614
  email: njk230@gmail.com
  # cv: http://cv.jarrekk.com  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-windows
    - name: icon-azure
  skill_icon2:
    - name: fa-github
    - name: icon-csharp
  desc: I am a student programmer. I love C# programming. I enjoy techiques of Mircosoft like .NET, Azure and Xamarin.  # Describe yourself.

# comment
disqus:
  name: nuwanda22
  public_key: UKkBbYt1IR5FJpkJ1RWIPVbisJT8QTe3KgGw2OXXxnUeE8HW7SavZDvXex7wrkTV

# analytics
## google analytics
ga:
  id: UA-87910638-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
